config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  get '/login' => 'auth#new', as: :login
  post '/login' => 'auth#login'
  get '/logout' => 'auth#logout', as: :logout

  get '/filter' => 'tasks#filter', as: :filter
  get '/search' => 'tasks#search', as: :search
  get '/mass_assign' => 'tasks#mass_assign', as: :mass_assign

  get '/getting_started' => 'home#started', as: :getting_started

  resources :users, except: [:index] do
    member do
      get 'switch_mode'
    end
  end

  resources :inboxes do
    resources :items, except: [:index]
    member do
      get 'develop' => 'develop#develop', as: :develop
    end
  end

  resources :projects do
    member do
      get 'archive'
      get 'unarchive'
    end
    resources :tasks, except: [:index] do
      member do
        get 'complete'
        get 'uncomplete'
        get 'edit_tags'
      end
    end
  end
  resources :tasks, only: [:index] #independent Task index
  resources :locations
  resources :tags

  resources :checklists do
    member do
      get 'printable'
    end
  end
  resources :print_checklists

  resources :folders do
    resources :ref_items, except: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  validates_with NameValidator

  has_many :ref_items, dependent: :destroy
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :mode
  before_action :set_folder, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :set_default_folder, only: [:destroy]

  # GET /folders
  # GET /folders.json
  def index
    if logged_in?
      @folders = Folder.where(user: @user).order(deletable: :asc, name: :asc)
    else
      redirect_to login_path
    end
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    if logged_in?
      @ref_items = @folder.ref_items.order(name: :asc)
    else
      redirect_to login_path
    end
  end

  # GET /folders/new
  def new
    if logged_in?
      @folder = Folder.new(user: @user)
    else
      redirect_to login_path
    end
  end

  # GET /folders/1/edit
  def edit
    if !(logged_in? && @folder.user == current_user)
      redirect_to login_path
    end
  end

  # POST /folders
  # POST /folders.json
  def create
    if logged_in?
      @folder = Folder.new(name: folder_params[:name], description: folder_params[:description], user:@user)
      if @folder.save
        if params[:develop] != nil
          @item = Item.find(params[:folder][:item_id])
          redirect_to develop_inbox_path(@item.inbox, item: @item.id, next_step: "added_folder", folder_id: @folder)
        else
          redirect_to folder_path(@folder)
        end
      else
        if params[:develop] != nil
          @item = Item.find(params[:folder][:item_id])
          @inbox = @item.inbox
          @step = "add_folder"
          render "develop/develop"
        else
          render 'new'
        end
      end
    else
      redirect_to login_path
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    if logged_in?
      if @folder.update(name: folder_params[:name], description: folder_params[:description], user:@user)
        redirect_to @folder
      else
        render 'edit'
      end
    else
      redirect_to login_path
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    if logged_in? && @folder.user == current_user
      @folder.ref_items.each do |item|
        item.update(folder: @default)
      end
      @folder.reload
      @folder.destroy
      redirect_to folders_path
    else
      redirect_to folders_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    def set_default_folder
      @default = Folder.where(user: @user, name: "General Reference").first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:name, :description)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= semantic_form_for @folder, :html => { class: "folder_form" } do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@folder.errors.count, "error") %> prohibited
        this folder from being saved:
      </h2>
      <ul>
        <% @folder.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs do %>
    <% if form_location == "develop" %>
      <%= f.hidden_field :item_id, as: :hidden, value: item.id %>
    <% end %>
    <%= f.input :name, required: true, :input_html => { class: @mode } %>
    <%= f.input :description, :input_html => { class: @mode } %>
    <%= f.actions do %>
      <%= f.action :submit, as: :input, :button_html => { class: "button #{@mode}", name: form_location  } %>
    <% end %>
  <% end %>
<% end %>

app/views/folders/edit.html.erb
<%= page_heading "Edit Reference Folder" %>

<%= render 'form', form_location: "edit" %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Show Folder', folder_path(@folder)  %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Folders', folders_path  %></button>
</div>

app/views/folders/index.html.erb
<p id="notice"><%= notice %></p>

<%= page_heading "Reference Folders" %>

<% if !(@folders.empty?) %>
  <table class="folders <%=@mode%>">
    <thead>
      <tr>
        <th>Folder Name</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @folders.each do |folder| %>
        <tr>
          <td><%= link_to folder.name, folder %></td>
          <% if folder.deletable %>
            <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
            <td><%= link_to 'Delete', folder, method: :delete, data: { confirm: 'Are you sure? All items associated with this folder will be reassigned to the General Reference Folder.' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

<% end %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'New Folder', new_folder_path %></button>
</div>

app/views/folders/new.html.erb
<%= page_heading "New Reference Folder" %>

<%= render 'form', form_location: "new" %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Folders', folders_path %></button
</div>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<%= page_heading "#{@folder.name} Reference Folder" %>

<% if @folder.deletable? %>
  <div class="folder_show_page">
    <p>
      <strong>Description:</strong>
      <%= @folder.description %>
    </p>
  </div>
<% end %>

<div class="nav_links">
  <% if @folder.deletable? %>
    <button class="button <%=@mode %>" type="button"><%= link_to 'Edit Reference Folder', edit_folder_path(@folder) %></button>
  <% end %>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Add Reference Item', new_folder_ref_item_path(@folder) %></button>
</div>

<% if !(@ref_items.empty?) %>
  <table class="items <%=@mode%>">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @ref_items.each do |item| %>
        <tr>
          <td><%= link_to item.name, folder_ref_item_path(@folder,item) %></td>
          <td><%= link_to 'Edit', edit_folder_ref_item_path(@folder,item) %></td>
          <td><%= link_to 'Delete', folder_ref_item_path(@folder,item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

  <br>

<div class="nav_links">
  <% if @folder.deletable? %>
    <button class="button <%=@mode %>" type="button"><%= link_to 'Delete Folder', @folder, method: :delete, data: { confirm: 'Are you sure? All items associated with this folder will be reassigned to the General Reference Folder.' } %></button>
  <% end %>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Folders', folders_path %></button>
</div>