config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  get '/login' => 'auth#new', as: :login
  post '/login' => 'auth#login'
  get '/logout' => 'auth#logout', as: :logout

  get '/filter' => 'tasks#filter', as: :filter
  get '/search' => 'tasks#search', as: :search
  get '/mass_assign' => 'tasks#mass_assign', as: :mass_assign

  get '/getting_started' => 'home#started', as: :getting_started

  resources :users, except: [:index] do
    member do
      get 'switch_mode'
    end
  end

  resources :inboxes do
    resources :items, except: [:index]
    member do
      get 'develop' => 'develop#develop', as: :develop
    end
  end

  resources :projects do
    member do
      get 'archive'
      get 'unarchive'
    end
    resources :tasks, except: [:index] do
      member do
        get 'complete'
        get 'uncomplete'
        get 'edit_tags'
      end
    end
  end
  resources :tasks, only: [:index] #independent Task index
  resources :locations
  resources :tags

  resources :checklists do
    member do
      get 'printable'
    end
  end
  resources :print_checklists

  resources :folders do
    resources :ref_items, except: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :tag_tasks, dependent: :destroy
  has_many :tasks, through: :tag_tasks
  validates_with NameValidator
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :location

  has_many :tag_tasks, dependent: :destroy
  has_many :tags, through: :tag_tasks

  accepts_nested_attributes_for :tag_tasks, :allow_destroy => true

  scope :all_tags, -> tag_ids {select { |p| p.has_all_tags(tag_ids) == true}}

  enum time: { five_min: 5, fifteen_min: 15, thirty_min: 30, fortyfive_min: 45, one_hr: 60, one_hr_thirty_min: 90, two_hr: 120, two_hr_thirty_min: 150, three_hr: 180, four_hr: 240 }

  enum energy: [:low, :medium, :high]

  def self.time_name(time)
    tn = { five_min: 5, fifteen_min: 15, thirty_min: 30, fortyfive_min: 45, one_hr: 60, one_hr_thirty_min: 90, two_hr: 120, two_hr_thirty_min: 150, three_hr: 180, four_hr: 240 }
    tn.key(time)
  end

  def self.time_names
    #time_names = { five_min: "5 min", fifteen_min: "15 min", thirty_min: "30 min", fortyfive_min: "45 min", one_hr: "1 hr", one_hr_thirty_min: "1 hr 30 min", two_hr: "2 hr", two_hr_thirty_min: "2 hr 30 min", three_hr: "3 hr", four_hr: "4 hr" }
    time_names = { "5 min" => 5, "15 min" => 15, "30 min" => 30, "45 min" => 45, "1 hr" => 60, "1 hr 30 min" => 90, "2 hr" => 120, "2 hr 30 min" => 150, "3 hr" => 180, "4 hr" => 240}
  end

  def time_read
    Task.time_names.key(Task.times[self.time])
  end

  def energy_read
    er_out = { "low": 0, "med": 1, "high": 2 }
    er_out.key(Task.energies[self.energy])
  end

  def complete
    self.update_attributes(completed: true)
  end

  def uncomplete
    self.update_attributes(completed: false)
  end

  def has_all_tags(tag_ids)
    has_all = true
    tag_ids.each do |tag|
      if !(self.tags.exists?(tag.to_i))
        has_all = false
      end
    end
    has_all
  end

  private
    def self.search(search,user)
      Task.joins(:project).where(projects: {user: user}).joins(:location).where("lower(tasks.name) LIKE :search OR lower(tasks.description) LIKE :search OR lower(projects.name) LIKE :search OR lower(projects.description) LIKE :search OR lower(locations.name) LIKE :search", search: "%#{search.downcase}%").distinct
    end

    def self.search_tags(search,user)
      Task.joins(:project).where(projects: {user: user}).joins(:tags).where("lower(tags.name) LIKE :search", search: "%#{search.downcase}%").distinct
    end

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :name, :password_digest, presence: true
  validates :email, uniqueness: { case_sensitive: false }
  validates :password, confirmation: { case_sensitive: true }

  has_many :inboxes, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :checklists, dependent: :destroy
  has_many :folders, dependent: :destroy
  has_many :print_checklists, dependent: :destroy

  before_save { |user| user.email = email.downcase }

  has_secure_password

  after_initialize do
    unless persisted?
      inboxes << Inbox.new(name: 'General', user: self, deletable: false, description: "If you decide to use this app as a single Digital Inbox, add all items to this Bin. If you decide to place items in many Bins before processing them into Tasks/Projects/etc., this Bin should be used for any items that don't fit in the other Bins you've made.")
      inboxes << Inbox.new(name: 'Someday/Maybe', user: self, deletable: false, description: "A place to put all items that should be revisited at another point in time or under different circumstances. Most items will start in another Bin and get moved here during processing. We recommend revisiting the items in this bin occasionally to see if they become relevant or can be deleted.")
      folders << Folder.new(name: 'General Reference', user: self, deletable: false)
      projects << Project.new(name: 'Unassigned', user: self, deletable: false)
      projects << Project.new(name: 'Single Step', user: self, deletable: false)
      locations << Location.new(name: 'Anywhere', user: self, deletable: false)
      checklists << Checklist.new(name: 'Waiting On', description: "For things that you are waiting on other people for.", user: self, deletable: false)
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :mode
  before_action :set_task, except: [:index, :new, :create, :filter, :search, :mass_assign]
  before_action :set_user
  before_action :set_default_project
  before_action :set_project, except: [:filter, :search, :mass_assign]
  before_action :set_default_location
  before_action :set_location, except: [:filter, :search, :mass_assign]
  before_action :time_collection, only: [:new, :edit, :create, :update, :filter, :search]
  before_action :energy_collection, only: [:new, :edit, :create, :update, :filter, :search]

  helper_method :sort_column, :sort_direction

  # GET /tasks
  # GET /tasks.json
  def index
    if logged_in?
      @tasks = Task.joins(:project).where(projects: {user: @user}).order(completed: :asc, name: :asc)
    else
      redirect_to login_path
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    if logged_in?
      @tags = @task.tags.order(name: :asc)
    else
      redirect_to login_path
    end
  end

  # GET /tasks/new
  def new
    if logged_in?
      @projects = Project.where(user: @user, archived: false).order(deletable: :asc, name: :asc)
      @locations = Location.where(user: @user)
      if params[:item_id] != nil
        item = Item.find(params[:item_id].to_i)
        @task = Task.new(name: item.name, description: item.description)
      else
        @task = Task.new
      end
    else
      redirect_to login_path
    end
  end

  # GET /tasks/1/edit
  def edit
    if !(logged_in? && @task.project.user == current_user)
      redirect_to login_path
    else
      @projects = Project.where(user: @user, archived: false).order(deletable: :asc, name: :asc)
      @locations = Location.where(user: @user).order(deletable: :asc, name: :asc)
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    if logged_in?
      @project = Project.find(task_params[:project_id])
      @projects = Project.where(user: @user, archived: false).order(deletable: :asc, name: :asc)
      @locations = Location.where(user: @user).order(deletable: :asc, name: :asc)
      if @project == nil
        @project = @default_project
      end
      @location = Location.find(task_params[:location_id])
      if @location == nil
        @location = @default_location
      end
      @task = Task.new(name: task_params[:name], description: task_params[:description], project: @project, location: @location, time: Task.time_name(task_params[:time].to_i), energy: @energy_collection.key(task_params[:energy].to_i))
      if @task.save
        if params[:develop] != nil
          @item = Item.find(params[:task][:item_id])
          redirect_to develop_inbox_path(@item.inbox, item: @item.id, project_id: @project, next_step: "added_task")
        else
          redirect_to project_task_path(@project,@task)
        end
      else
        if params[:develop] != nil
          @item = Item.find(params[:task][:item_id])
          @step = "add_task"
          render "develop/develop"
        else
          render 'new'
        end
      end
    else
      redirect_to login_path
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    if logged_in?
      if params[:commit] == "Save Tags"
        @projects = Project.where(user: @user, archived: false).order(deletable: :asc, name: :asc)
        @locations = Location.where(user: @user).order(deletable: :asc, name: :asc)
        if task_params[:tag_ids] == nil
          @task.tag_tasks.each do |tag_task|
            tag_task.destroy
          end
          redirect_to project_task_path(@project,@task)
        else
          if @task.update(task_params)
            redirect_to project_task_path(@project,@task)
          else
            render 'edit_tags'
          end
        end
      else
        @projects = Project.where(user: @user, archived: false).order(deletable: :asc, name: :asc)
        @locations = Location.where(user: @user).order(deletable: :asc, name: :asc)
        if @task.update(name: task_params[:name], description: task_params[:description], project: @project, location: @location, time: Task.time_name(task_params[:time].to_i), energy: @energy_collection.key(task_params[:energy].to_i))
          redirect_to project_task_path(@project,@task)
        else
          render 'edit'
        end
      end
    else
      redirect_to login_path
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    if logged_in? && @task.user == current_user
      @task.destroy
      redirect_to projects_path
    else
      redirect_to projects_path
    end
  end

  def complete
    if logged_in? && @task.project.user == current_user
      @task.complete
      redirect_to project_path(@project)
    else
      redirect_to projects_path
    end
  end

  def uncomplete
    if logged_in? && @task.project.user == current_user
      @task.uncomplete
      redirect_to project_task_path(@project,@task)
    else
      redirect_to projects_path
    end
  end

  def edit_tags
    @tags = Tag.where(user: @user)
  end

  def filter
    if params[:commit] == "Filter"
      # Perform filter
      all_tasks = Task.joins(:project).where(projects: {user: @user})

      # Include archived?
      if params[:archived] == nil || params[:archived] != "1"
        all_tasks = all_tasks.where(projects: {archived: false})
      end

      # Include completed?
      if params[:completed] == nil || params[:completed] != "1"
        all_tasks = all_tasks.where(completed: false)
      end

      # Location
      @location = Location.find(params[:location_id])
      loc_tasks = all_tasks.where(location: @location)
      # Include Anywhere?
      if params[:anywhere] != nil && params[:anywhere] == "1"
        any_tasks = all_tasks.where(location: @default_location)
        loc_tasks = loc_tasks.or(any_tasks).distinct
      end

      # Time (includes all tasks of lower time with sorting to put highest time first)
      time_tasks = Task.none
      @time_collection.each do |k,v|
        if v <= params[:time].to_i
          time_tasks = time_tasks.or(loc_tasks.where(time: v))
        end
      end
      time_tasks = time_tasks.order(time: :desc)

      # Energy (includes all tasks of lower energy with sorting to put highest energy first)
      energy_tasks = Task.none
      @energy_collection.each do |k,v|
        if v <= params[:energy].to_i
          energy_tasks = energy_tasks.or(time_tasks.where(energy: v.to_i))
        end
      end

      # Tags
      tagged_tasks = energy_tasks
      if params[:task] != nil && params[:task][:tag_ids] != nil
        tagged_tasks = Task.none
        energy_tasks.each do |task|
          if task.has_all_tags(params[:task][:tag_ids])
            tagged_tasks = tagged_tasks.or(energy_tasks.where(id: task.id))
          end
        end
      end

      @tasks = tagged_tasks.order(time: :desc, energy: :desc, completed: :asc, name: :asc)

      @ids = []
      if !(@tasks.empty?)
        @tasks.each do |task|
          @ids << task.id
        end
      end
      render 'filter_results'
    else
      # Render filter
      @locations = Location.where(user: @user)
      @tags = Tag.where(user: @user)
    end
  end

  def search
    if params[:commit] == "Search"
      # Perform search
      tasks_nd = Task.search(params[:keyword],@user)
      tasks_tags = Task.search_tags(params[:keyword],@user)

      @tasks = Task.none
      @ids = []
      if !(tasks_nd.empty?)
        tasks_nd.each do |task|
          @ids << task.id
        end
      end
      if !(tasks_tags.empty?)
        tasks_tags.each do |task|
          @ids << task.id
        end
      end

      @tasks = Task.where(id: @ids)

      # Include archived?
      if params[:archived] == nil || params[:archived] != "1"
        @tasks = @tasks.joins(:project).where(projects: {archived: false})
      end

      # Include completed?
      if params[:completed] == nil || params[:completed] != "1"
        @tasks = @tasks.where(completed: false)
      end

      if !(@tasks.empty?)
        @tasks.each do |task|
          @ids << task.id
        end
      end

      render 'search_results'
    else
      # Render search
    end
  end

  def mass_assign
    if params[:commit] == nil
      ids = []
      params[:task_ids].each do |id|
        ids << id.to_i
      end
      @tasks = Task.where(id: ids)
      @tags = Tag.where(user: @user)
      @from = params[:from]
    else
      if params[:task] != nil && params[:task][:ids] != nil
        params[:task][:ids].each do |id|
          task = Task.find(id)
          if task.project.user == @user
            if params[:task][:tag_ids] != nil
              params[:task][:tag_ids].each do |tag_id|
                tag = Tag.find(tag_id)
                if tag.user == @user
                  if task.tags.where(id: tag.id).empty?
                    tag_task = TagTask.new(tag: tag, task: task)
                    tag_task.save
                  end
                end
              end
            end
          end
        end
      end
      if params[:from] == "filter"
        redirect_to :filter
      elsif params[:from] == "search"
        redirect_to :search
      elsif params[:from].start_with?("project")
        string_arr = params["from"].split("_")
        project = Project.find(string_arr.second.to_i)
        redirect_to project_path(project)
      else
        redirect_to root_path
      end
      # Need to figure out way to confirm that tags were added
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    def set_project
      if params.has_key?(:project_id)
        @project = Project.find(params[:project_id])
        if @project.user != current_user
          @project = @default_project
        end
      elsif params[:task] != nil && params[:task].has_key?(:project_id)

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= semantic_form_for [@project,@task], html: { class: "task_form" } do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs do %>
    <% if form_location == "develop" %>
      <%= f.hidden_field :item_id, as: :hidden, value: item.id %>
    <% end %>
    <%= f.input :name, :input_html => { class: @mode } %>
    <%= f.input :description, :input_html => { class: @mode } %>
    <label>
      Time:
      <%= f.select(:time, options_for_select(@time_collection, Task.times[@task.time]), {}, { class: @mode }) %>
    </label>
    <br>
    <label>
      Energy Level:
      <%= f.select(:energy, options_for_select(@energy_collection, Task.energies[@task.energy]), {}, { class: @mode }) %>
    </label>
    <br>
    <label>
      Project:
      <%= f.select(:project_id, options_for_select(@projects.map{|t| [t.name, t.id]}, @project.id), {}, { class: @mode }) %>
    </label>
    <br>
    <label>
      Location:
      <%= f.select(:location_id, options_for_select(@locations.map{|t| [t.name, t.id]}, @location.id), {}, { class: @mode }) %>
    </label>

    <%= f.actions do %>
      <%= f.action :submit, as: :input, button_html: { class: "button #{@mode}", name: form_location }  %>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/_tag_form.html.erb
<%= semantic_form_for [@project,task], html: { class: "tag_task_form" } do |f| %>
  <%= f.inputs do %>
    <%= f.input :id, as: :hidden, value: task.id %>
    <%= f.label "Tags", class: "tag_label" %><br />
    <%= render "tags_checkboxes", tags: @tags, task: task %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, as: :input, label: "Save Tags", button_html: { class: "button #{@mode}" } %>
  <% end %>
<% end %>

app/views/tasks/_tags_checkboxes.html.erb
<ul class="checkbox-grid">
  <% tags.each do |tag| %>
    <% if task != nil %>
      <% checked = task.tags.exists?(id: tag.id) %>
    <% else %>
      <% checked = false %>
    <% end %>
    <li>
      <label>
        <%= check_box_tag "task[tag_ids][]", tag.id, checked, class: "checkbox" %>
        <%= tag.name %>
      </label>
    </li>
  <% end %>
</ul>

app/views/tasks/edit.html.erb
<%= page_heading "Edit Task" %>

<%= render 'form', form_location: "new" %>

<%= link_to 'Show Task', project_task_path(@project,@task) %> |
<%= link_to 'Back to Project', @project %> |
<%= link_to 'Back to Projects', projects_path %> | <%= link_to 'Back to Location', @location %> |
<%= link_to 'Back to Locations', locations_path %>

app/views/tasks/edit_tags.html.erb
<%= page_heading "Add/Remove Tags" %>

<%= render 'tag_form', task: @task %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Show Task', project_task_path(@project,@task) %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Make Another Tag (Refresh this page after making new tags)', new_tag_path, target: '_blank' %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Project', @project %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Projects', projects_path %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Location', @location %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Locations', locations_path %></button>
</div>

app/views/tasks/filter.html.erb
<%= page_heading "Filter Tasks" %>

<div class="filter_form">
  <%= form_tag filter_path, method: :get do %>
    <div class="location">
      <% # Location -- include Anywhere? %>
      <label>
        Where are you?
        <%= select_tag(:location_id, options_for_select(@locations.map { |loc| [loc.name, loc.id] }), { class: @mode }) %>
      </label>
      <label>
        Also include Anywhere?
        <%= check_box_tag :anywhere, 1, false, class: "checkbox" %>
      </label>
    </div>

    <div class="time">
      <% # How much time do you have? -- Present highest that meets criteria first, lowest last  %>
      <label>
        How much time do you have?
        <%= select_tag(:time, options_for_select(@time_collection), { class: @mode }) %>
      </label>
    </div>

    <div class="energy">
      <% # How much energy do you have? -- Present highest that meets criteria first, lowest last  %>
      <label>
        What level of energy do you have?
        <%= select_tag(:energy, options_for_select(@energy_collection), { class: @mode }) %>
      </label>
    </div>

    <div class="tags">
      <% if !(@tags.empty?) %>
      Select Tags that Tasks should match
      <% # choose tags %>
        <%= render "tags_checkboxes", tags: @tags, task: nil %>
      <% end %>
    </div>

    <div class="other">
      <% # Include archived projects? %>
      <label>
        Include archived projects?
        <%= check_box_tag :archived, 1, false, class: "checkbox" %>
      </label>
      <% # Include completed tasks? %>
      <label>
        Include completed tasks?
        <%= check_box_tag :completed, 1, false, class: "checkbox" %>
      </label>
    </div>

    <%= submit_tag "Filter", class: "button #{@mode}" %>
  <% end %>
</div>

app/views/tasks/filter_results.html.erb
<%= page_heading "Filter Results" %>

<%= render 'task_table', tasks: @tasks, proj_name: true, loc_name: false, options: false, time_en: true, selecting: false %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to "New Filter", filter_path %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to "Mass Assign Tags", mass_assign_path(task_ids: @ids, from: "filter") %></button>
</div>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<%= page_heading "Tasks" %>

<%= render 'task_table', tasks: @tasks, proj_name: false, loc_name: true, options: false, time_en: true, selecting: false %>
<br>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'New Task', new_project_task_path(@project) %></button>
</div>

app/views/tasks/mass_assign.html.erb
<%= page_heading "Mass Assign Tags" %>

<div class="mass_assign">
  <%= form_tag mass_assign_path, method: :get do %>
    <%= render 'task_table', tasks: @tasks, proj_name: false, loc_name: false, options: false, time_en: false, selecting: true %>

    <div class="tags">
      Tags
      <%= render 'tags_checkboxes', tags: @tags, task: nil %>
    </div>
    <%= hidden_field_tag 'from', @from %>
    <%= submit_tag "Mass Assign", class: "button #{@mode}" %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<%= page_heading "New Task" %>

<%= render 'form', form_location: "new" %>

<%= link_to 'Back to Project', @project %> |
<%= link_to 'Back to Projects', projects_path %> | <%= link_to 'Back to Location', @location %> |
<%= link_to 'Back to Locations', locations_path %>

app/views/tasks/results.html.erb
<%= page_heading "Filter Results" %>

<%= render 'task_table', tasks: @tasks, proj_name: true, loc_name: false, options: false, time_en: true %>

<div class="nav_links">
  <%= link_to "New Search", search_path %>
</div>

app/views/tasks/search.html.erb
<%= page_heading "Search Tasks" %>

<div class="search_form">
  <%= form_tag search_path, method: :get do %>
    <label>
      Keyword:
      <%= text_field_tag :keyword, "", class: "text" %>
    </label>
    <div class="other">
      <% # Include archived projects? %>
      <label>
        Include archived projects?
        <%= check_box_tag :archived, 1, false, class: "checkbox" %>
      </label>
      <% # Include completed tasks? %>
      <label>
        Include completed tasks?
        <%= check_box_tag :completed, 1, false, class: "checkbox" %>
      </label>
    </div>

    <%= submit_tag "Search", class: "button #{@mode}" %>
  <% end %>
</div>

app/views/tasks/search_results.html.erb
<%= page_heading "Search Results" %>

<%= render 'task_table', tasks: @tasks, proj_name: true, loc_name: false, options: false, time_en: true, selecting: false %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to "New Search", search_path %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to "Mass Assign Tags", mass_assign_path(task_ids: @ids, from: "filter") %></button>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= page_heading "#{@task.name}" %>

<div class="task_show_page">
  <p>
    <strong>Project:</strong>
    <%= @project.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @location.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @task.description %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= Task.time_names.key(Task.times[@task.time]) %>
  </p>

  <p>
    <strong>Energy:</strong>
    <%= @task.energy %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= @task.completed %>
  </p>
</div>

<% if !(@tags.empty?) %>
  <p>
    <strong>Tags:</strong>
    <% @tags.each do |tag| %>
      <%= link_to tag.name, tag %>
    <% end %>
  </p>
<% end %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Edit Task', edit_project_task_path(@project,@task) %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Add/Remove Tags', edit_tags_project_task_path(@project,@task) %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Add Another Task', new_project_task_path(@project, location_id: @location) %></button>
  <% if @task.completed? %>
    <button class="button <%=@mode %>" type="button"><%= link_to 'Mark Task Uncompleted', uncomplete_project_task_path(@project,@task) %></button>
  <% end %>
  <% if !(@task.completed?) %>
    <button class="button <%=@mode %>" type="button"><%= link_to 'Mark Task Completed', complete_project_task_path(@project,@task) %></button>
  <% end %>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Project', project_path(@project) %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Location', location_path(@location) %></button>
</div>