config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  get '/login' => 'auth#new', as: :login
  post '/login' => 'auth#login'
  get '/logout' => 'auth#logout', as: :logout

  get '/filter' => 'tasks#filter', as: :filter
  get '/search' => 'tasks#search', as: :search
  get '/mass_assign' => 'tasks#mass_assign', as: :mass_assign

  get '/getting_started' => 'home#started', as: :getting_started

  resources :users, except: [:index] do
    member do
      get 'switch_mode'
    end
  end

  resources :inboxes do
    resources :items, except: [:index]
    member do
      get 'develop' => 'develop#develop', as: :develop
    end
  end

  resources :projects do
    member do
      get 'archive'
      get 'unarchive'
    end
    resources :tasks, except: [:index] do
      member do
        get 'complete'
        get 'uncomplete'
        get 'edit_tags'
      end
    end
  end
  resources :tasks, only: [:index] #independent Task index
  resources :locations
  resources :tags

  resources :checklists do
    member do
      get 'printable'
    end
  end
  resources :print_checklists

  resources :folders do
    resources :ref_items, except: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  validates_with NameValidator

  has_many :tasks, dependent: :destroy

  def archive
    if self.deletable?
      self.update_attributes(archived: true)
    end
  end

  def unarchive
    self.update_attributes(archived: false)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :mode
  before_action :set_project, only: [:show, :edit, :update, :destroy, :archive, :unarchive]
  before_action :set_user
  before_action :set_default_project, only: [:destroy]
  before_action :set_default_location, only: [:show]

  # GET /projects
  # GET /projects.json
  def index
    if logged_in?
      @projects = Project.where(user: @user).order(deletable: :asc, archived: :asc, name: :asc)
    else
      redirect_to login_path
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if logged_in?
      @tasks = @project.tasks.order(completed: :asc, name: :asc)
      @ids = []
      if !(@tasks.empty?)
        @tasks.each do |task|
          @ids << task.id
        end
      end
    else
      redirect_to login_path
    end
  end

  # GET /projects/new
  def new
    if logged_in?
      if params[:item_id] != nil
        item = Item.find(params[:item_id].to_i)
        @project = Project.new(user: @user, name: item.name, description: item.description)
      else
        @project = Project.new(user: @user)
      end
    else
      redirect_to login_path
    end
  end

  # GET /projects/1/edit
  def edit
    if !(logged_in? && @project.user == current_user)
      redirect_to login_path
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    if logged_in?
      @project = Project.new(name: project_params[:name], description: project_params[:description], user:@user)
      if @project.save
        if params[:develop] != nil
          @item = Item.find(params[:project][:item_id])
          redirect_to develop_inbox_path(@item.inbox, item: @item.id, next_step: "started_project", project_id: @project)
        else
          redirect_to project_path(@project)
        end
      else
        if params[:develop] != nil
          @item = Item.find(params[:project][:item_id])
          @inbox = @item.inbox
          @step = "start_project"
          render "develop/develop"
        else
          render 'new'
        end
      end
    else
      redirect_to login_path
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if logged_in? && @project.user == current_user
      if @project.update(name: project_params[:name], description: project_params[:description], user: @user)
        redirect_to @project
      else
        render 'edit'
      end
    else
      redirect_to login_path
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    if logged_in? && @project.user == current_user && @project.deletable?
      @project.destroy
      redirect_to projects_path
    else
      redirect_to projects_path
    end
  end

  def archive
    if logged_in? && @project.user == current_user
      if @project.deletable?
        @project.archive
      end
      redirect_to projects_path
    else
      redirect_to projects_path
    end
  end

  def unarchive
    if logged_in? && @project.user == current_user
      @project.unarchive
      redirect_to @project
    else
      redirect_to projects_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    def set_default_project
      @default = Project.where(user: @user, name: "Unassigned").first
    end

    def set_default_location
      @default_location = Location.where(user: @user, name: "Anywhere").first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= semantic_form_for @project, :html => { class: "project_form" } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs do %>
    <% if form_location == "develop" %>
      <%= f.hidden_field :item_id, as: :hidden, value: item.id %>
    <% end %>
    <%= f.input :name, required: true, :input_html => { class: @mode }  %>
    <%= f.input :description, :input_html => { class: @mode } %>
    <%= f.actions do %>
      <%= f.action :submit, :as => :input, :button_html => { class: "button #{@mode}", name: form_location }  %>
    <% end %>
  <% end %>
<% end %>

app/views/projects/edit.html.erb
<%= page_heading "Editing Project" %>

<%= render 'form', form_location: "edit" %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Show Project', @project %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Projects', projects_path %></button>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<%= page_heading "Projects" %>

<% if !(@projects.empty?) %>
  <table class="projects <%=@mode%>">
    <thead>
      <tr>
        <th>Project Name</th>
        <th colspan="3" class="options"></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project %></td>
          <% if project.deletable? %>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure? All tasks associated with this project will also be deleted (Projects can be archived instead).' } %></td>
          <% end %>
          <% if project.archived? %>
            <td><%= link_to 'Unarchive', unarchive_project_path(project) %></td>
          <% end %>
          <% if project.deletable? && !(project.archived?) %>
            <td><%= link_to 'Archive', archive_project_path(project) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

<% end %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'New Project', new_project_path %></button>
</div>

app/views/projects/new.html.erb
<%= page_heading "New Project" %>

<%= render 'form', form_location: "new" %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Projects', projects_path %></button>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= page_heading "#{@project.name}" %>

<div class="nav_links">
  <% if @project.deletable? %>
    <button class="button <%=@mode %>" type="button"><%= link_to 'Edit Project', edit_project_path(@project) %></button>
  <% end %>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Add Task', new_project_task_path(@project, location_id: @default_location) %></button>
</div>

<% if @project.deletable? %>
  <div class="project_show_page">
    <p>
      <strong>Description:</strong>
      <%= @project.description %>
    </p>
  </div>
<% end %>

<%= render 'task_table', tasks: @tasks, proj_name: false, loc_name: true, options: false, time_en: true, selecting: false %>
<br>

<div class="nav_links">
  <% if @project.deletable? %>
    <button class="button <%=@mode %>" type="button"><%= link_to 'Delete Project', @project, method: :delete, data: { confirm: 'Are you sure? All tasks associated with this project will also be deleted (Projects can be archived instead).' } %></button>
  <% end %>
  <% if @project.archived? %>
    <button class="button <%=@mode %>" type="button"><%= link_to 'Unarchive Project', unarchive_project_path(@project) %></button>
  <% end %>
  <% if @project.deletable? && !(@project.archived?) %>
    <button class="button <%=@mode %>" type="button"><%= link_to 'Archive Project', archive_project_path(@project) %></button>
  <% end %>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Projects', projects_path %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to "Mass Assign Tags", mass_assign_path(task_ids: @ids, from: "project_#{@project.id}") %></button>
</div>