config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  get '/login' => 'auth#new', as: :login
  post '/login' => 'auth#login'
  get '/logout' => 'auth#logout', as: :logout

  get '/filter' => 'tasks#filter', as: :filter
  get '/search' => 'tasks#search', as: :search
  get '/mass_assign' => 'tasks#mass_assign', as: :mass_assign

  get '/getting_started' => 'home#started', as: :getting_started

  resources :users, except: [:index] do
    member do
      get 'switch_mode'
    end
  end

  resources :inboxes do
    resources :items, except: [:index]
    member do
      get 'develop' => 'develop#develop', as: :develop
    end
  end

  resources :projects do
    member do
      get 'archive'
      get 'unarchive'
    end
    resources :tasks, except: [:index] do
      member do
        get 'complete'
        get 'uncomplete'
        get 'edit_tags'
      end
    end
  end
  resources :tasks, only: [:index] #independent Task index
  resources :locations
  resources :tags

  resources :checklists do
    member do
      get 'printable'
    end
  end
  resources :print_checklists

  resources :folders do
    resources :ref_items, except: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ref_item.rb
class RefItem < ApplicationRecord
  belongs_to :folder
end

app/controllers/ref_items_controller.rb
class RefItemsController < ApplicationController
  before_action :mode
  before_action :set_ref_item, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :set_default_folder
  before_action :set_folder

  # GET /ref_items
  # GET /ref_items.json
  # def index
  #   @ref_items = RefItem.all
  # end

  # GET /ref_items/1
  # GET /ref_items/1.json
  def show
    if logged_in?
    else
      redirect_to login_path
    end
  end

  # GET /ref_items/new
  def new
    if logged_in?
      @ref_item = RefItem.new
      @folders = Folder.where(user: @user).order(deletable: :asc, name: :asc)
    else
      redirect_to login_path
    end
  end

  # GET /ref_items/1/edit
  def edit
    if !(logged_in? && @ref_item.folder.user == current_user)
      redirect_to login_path
    else
      @folders = Folder.where(user: @user).order(deletable: :asc, name: :asc)
    end
  end

  # POST /ref_items
  # POST /ref_items.json
  def create
    if logged_in?
      @ref_item = RefItem.new(ref_item_params)

      if @ref_item.save
        if params[:develop] != nil
          @item = Item.find(params[:ref_item][:item_id])
          redirect_to develop_inbox_path(@item.inbox, item: @item.id, next_step: "added_ref_item", folder_id: @folder)
        else
          redirect_to folder_ref_item_path(@folder,@ref_item)
        end
      else
        if params[:develop] != nil
          @item = Item.find(params[:ref_item][:item_id])
          @step = "add_ref_item"
          render "develop/develop"
        else
          @folders = Folder.where(user: @user).order(deletable: :asc, name: :asc)
          render 'new'
        end
      end
    else
      redirect_to login_path
    end
  end

  # PATCH/PUT /ref_items/1
  # PATCH/PUT /ref_items/1.json
  def update
    if logged_in?
      if @ref_item.update(ref_item_params)
        redirect_to folder_ref_item_path(@folder,@ref_item)
      else
        @folders = Folder.where(user: @user).order(deletable: :asc, name: :asc)
        render 'edit'
      end
    else
      redirect_to login_path
    end
  end

  # DELETE /ref_items/1
  # DELETE /ref_items/1.json
  def destroy
    if logged_in? && @ref_item.folder.user == current_user
      @ref_item.destroy
      redirect_to folders_path
    else
      redirect_to folders_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ref_item
      @ref_item = RefItem.find(params[:id])
    end

    def set_folder
      if params.has_key?(:folder_id)
        @folder = Folder.find(params[:folder_id])
        if @folder.user != current_user
          @folder = @default
        end
      else
        @folder = @ref_item.folder
        if @folder == nil
          @folder = @default
        end
      end
    end

    def set_user
      @user = current_user
    end

    def set_default_folder
      @default = Folder.where(user: @user, name: "General Reference").first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ref_item_params
      params.require(:ref_item).permit(:name, :description, :folder_id)
    end
end

app/helpers/ref_items_helper.rb
module RefItemsHelper
end

app/views/ref_items/_form.html.erb
<%= semantic_form_for [@folder, @ref_item], :html => { class: "ref_item_form" } do |f| %>
  <% if @ref_item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@ref_item.errors.count, "error") %> prohibited
        this reference item from being saved:
      </h2>
      <ul>
        <% @ref_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs do %>
    <% if form_location == "develop" %>
      <%= f.hidden_field :item_id, as: :hidden, value: item.id %>
    <% end %>
    <%= f.input :name, required: true, :input_html => { class: @mode } %>
    <%= f.input :description, :input_html => { class: @mode } %>
    <%= f.select(:folder_id, options_for_select(@folders.map{|t| [t.name, t.id]}, @folder.id), {}, { class: @mode }) %>
    <%= f.actions do %>
      <%= f.action :submit, as: :input, :button_html => { class: "button #{@mode}", name: form_location } %>
    <% end %>
  <% end %>
<% end %>

app/views/ref_items/edit.html.erb
<%= page_heading "Edit Reference Item" %>

<%= render 'form' %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Show Reference Item', folder_ref_item_path(@folder,@ref_item) %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Folder', @folder %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Folders', folders_path %></button>
</div>

app/views/ref_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ref Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Folder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ref_items.each do |ref_item| %>
      <tr>
        <td><%= ref_item.name %></td>
        <td><%= ref_item.description %></td>
        <td><%= ref_item.folder %></td>
        <td><%= link_to 'Show', ref_item %></td>
        <td><%= link_to 'Edit', edit_ref_item_path(ref_item) %></td>
        <td><%= link_to 'Destroy', ref_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ref Item', new_ref_item_path %>

app/views/ref_items/new.html.erb
<%= page_heading "New Reference Item" %>

<%= render 'form' %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Folder', @folder %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Folders', folders_path %></button>
</div>

app/views/ref_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= page_heading "#{@ref_item.name}" %>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Edit Reference Item', edit_folder_ref_item_path(@folder,@ref_item) %></button>
</div>

<div class="ref_item_show_page">
  <p>
    <strong>Description:</strong>
    <%= @ref_item.description %>
  </p>

  <p>
    <strong>Folder:</strong>
    <%= @ref_item.folder.name %>
  </p>
</div>

<div class="nav_links">
  <button class="button <%=@mode %>" type="button"><%= link_to 'Add Another Reference Item', new_folder_ref_item_path(@folder) %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Folder', @folder %></button>
  <button class="button <%=@mode %>" type="button"><%= link_to 'Back to Folders', folders_path %></button>
</div>